#tag BuildAutomation
			Begin BuildStepList Linux
				Begin BuildProjectStep Build
				End
				Begin CopyFilesBuildStep CopyResources32bit
					AppliesTo = 3
					Architecture = 0
					Destination = 1
					Subdirectory = 
					FolderItem = Li4vUHJvZmlsZXMv
					FolderItem = Li4vR2VuZXRpYy5jb2Rlcw==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2xpYndlYmtpdDMyLw==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL1RyYW5zVGVybUhQL2V4cHRlcm0uZGF0
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL0xpbnV4L3RyYW5zdGVybQ==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2JsYW5rLmh0bWw=
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL0xpbnV4L01FTUUvbWFzdA==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL0xpbnV4L01FTUUvbWVtZQ==
					FolderItem = Li4vZ2Vub21lU3RhdHMuSlNPTg==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL0htbWVyVXNlckd1aWRlLnBkZg==
					FolderItem = Li4vSGVscC8=
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL1JlZ3Vsb25EQi8=
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL0xpbnV4L3RmYXN0eA==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL0xpbnV4L2FsaW1hc2s=
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL0xpbnV4L2htbWJ1aWxk
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL0xpbnV4L25obW1lcg==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL01hYy9tZW1lX3htbF90b19odG1s
					FolderItem = Li4vUHl0aG9uL2diazJ0YmwucHk=
					FolderItem = Li4vUHl0aG9uL2dlbmVwYXJzZS5weQ==
					FolderItem = Li4vUHl0aG9uL0htbUdlbi5weQ==
					FolderItem = Li4vUHl0aG9uL01hc3RHZW4ucHk=
					FolderItem = Li4vUHl0aG9uL09wZXJPbi5weQ==
					FolderItem = Li4vUHl0aG9uL3B0dF9jb252ZXJ0ZXIucHk=
					FolderItem = 
					FolderItem = Li4vVEZfSE1Ncy8=
					FolderItem = Li4vUHl0aG9uL0Jpb1B5dGhvblZlcnNpb24ucHk=
					FolderItem = Li4vLi4vLi4vRGVza3RvcC9Qcm90RmFtaWx5LnB5
					FolderItem = Li4vUHl0aG9uL1JlcGVhdEdlbi5weQ==
					FolderItem = Li4vLi4vQ1J0YWdCYXNlLw==
					FolderItem = Li4vLi4vUmVnUHJlY2lzZUV4cG9ydC8=
					FolderItem = Li4vUHl0aG9uL3VuaXByb3QyZ2VucGVwdC5weQ==
					FolderItem = Li4vUHl0aG9uL3RmX2NsYXNzaWZpZXIucHk=
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2htbWxpYkwuaG1t
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2htbWxpYkwuaG1tLmgzZg==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2htbWxpYkwuaG1tLmgzaQ==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2htbWxpYkwuaG1tLmgzbQ==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2htbWxpYkwuaG1tLmgzcA==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL25obW1lcl9saWIuaG1t
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL25obW1lcl9saWIuaG1tLmgzZg==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL25obW1lcl9saWIuaG1tLmgzaQ==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL25obW1lcl9saWIuaG1tLmgzbQ==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL25obW1lcl9saWIuaG1tLmgzcA==
					FolderItem = Li4vUHl0aG9uL2FkZF90ZmJzX3RvX2diay5weQ==
				End
				Begin CopyFilesBuildStep Copy2AppFolder
					AppliesTo = 1
					Architecture = 0
					Destination = 0
					Subdirectory = 
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL0luc3RhbGwuaHRtbA==
				End
				Begin CopyFilesBuildStep CopyResources64bit
					AppliesTo = 0
					Architecture = 0
					Destination = 1
					Subdirectory = 
					FolderItem = Li4vR2VuZXRpYy5jb2Rlcw==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL1RyYW5zVGVybUhQL2V4cHRlcm0uZGF0
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2JsYW5rLmh0bWw=
					FolderItem = Li4vZ2Vub21lU3RhdHMuSlNPTg==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL0htbWVyVXNlckd1aWRlLnBkZg==
					FolderItem = Li4vSGVscC8=
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL1JlZ3Vsb25EQi8=
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL0xpbnV4NjRiaXQvYWxpbWFzaw==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL0xpbnV4NjRiaXQvaG1tYnVpbGQ=
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL0xpbnV4NjRiaXQvbWFzdA==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL0xpbnV4NjRiaXQvbWVtZQ==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL0xpbnV4NjRiaXQvbmhtbWVy
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL0xpbnV4NjRiaXQvdHJhbnN0ZXJt
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL0xpbnV4NjRiaXQvdGZhc3R4
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL01hYy9tZW1lX3htbF90b19odG1s
					FolderItem = Li4vUHl0aG9uL2diazJ0YmwucHk=
					FolderItem = Li4vUHl0aG9uL2dlbmVwYXJzZS5weQ==
					FolderItem = Li4vUHl0aG9uL0htbUdlbi5weQ==
					FolderItem = Li4vUHl0aG9uL01hc3RHZW4ucHk=
					FolderItem = Li4vUHl0aG9uL09wZXJPbi5weQ==
					FolderItem = Li4vUHl0aG9uL3B0dF9jb252ZXJ0ZXIucHk=
					FolderItem = Li4vVEZfSE1Ncy8=
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL0xpbnV4NjRiaXQvY2QtaGl0LWVzdA==
					FolderItem = Li4vVEZfZmFtaWxpZXMv
					FolderItem = Li4vUHl0aG9uL0Jpb1B5dGhvblZlcnNpb24ucHk=
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL0xpbnV4NjRiaXQvaG1tc2VhcmNo
					FolderItem = Li4vUHl0aG9uL1JlcGVhdEdlbi5weQ==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL0xpbnV4NjRiaXQvbWVzaGNsdXN0
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2NvbGxlY3RmX2V4cG9ydC50c3Y=
					FolderItem = Li4vUHl0aG9uL1Byb3RGYW1pbFkucHk=
					FolderItem = Li4vUHl0aG9uL2dldHByb3QucHk=
					FolderItem = Li4vLi4vQ2FsaWJyYXRlZFByb2ZpbGVzLw==
					FolderItem = Li4vUHl0aG9uL3VuaXByb3QyZ2VucGVwdC5weQ==
					FolderItem = Li4vLi4vQ1J0YWdCYXNlLw==
					FolderItem = Li4vUHJvZmlsZXMv
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL0xpbnV4NjRiaXQvdGZhc3R4
					FolderItem = Li4vUmVnUHJlY2lzZURhdGEv
					FolderItem = Li4vUHl0aG9uL0V4dHJhY3RGcmFnbWVudC5weQ==
					FolderItem = Li4vUHl0aG9uL1Rlcm1HZW4ucHk=
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2htbWxpYi5obW0=
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2htbWxpYi5obW0uaDNm
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2htbWxpYi5obW0uaDNp
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2htbWxpYi5obW0uaDNt
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2htbWxpYi5obW0uaDNw
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL0NvcnluZVJlZ05ldC8=
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2htbWxpYkwuaG1t
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2htbWxpYkwuaG1tLmgzZg==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2htbWxpYkwuaG1tLmgzaQ==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2htbWxpYkwuaG1tLmgzbQ==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2htbWxpYkwuaG1tLmgzcA==
					FolderItem = Li4vUHl0aG9uL21hdGNoZXNfc2NvcmVfYW5hbHlzaXMucHk=
					FolderItem = Li4vUHl0aG9uL2NvbGxlY3Rfc3RhdHMucHk=
					FolderItem = Li4vUHl0aG9uL3RmX2NsYXNzaWZpZXIucHk=
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL25obW1lcl9saWIuaG1t
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL25obW1lcl9saWIuaG1tLmgzZg==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL25obW1lcl9saWIuaG1tLmgzaQ==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL25obW1lcl9saWIuaG1tLmgzbQ==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL25obW1lcl9saWIuaG1tLmgzcA==
					FolderItem = Li4vUHl0aG9uL2FkZF90ZmJzX3RvX2diay5weQ==
				End
				Begin IDEScriptBuildStep Zip , AppliesTo = 2, Architecture = 0
					'Dim result As String
					'result = DoShellCommand("cd " + currentBuildLocation + " && zip -r SigmoID.zip SigmoID"
				End
				Begin CopyFilesBuildStep CopyLibs
					AppliesTo = 0
					Architecture = 0
					Destination = 2
					Subdirectory = 
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL0xpbnV4NjRiaXQvTGlidW53aW5kL2xpYjY0L2xpYnVud2luZC14ODZfNjQuc28uOA==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL0xpbnV4NjRiaXQvTGlidW53aW5kL2xpYjY0L2xpYnVud2luZC5zby44
				End
			End
			Begin BuildStepList Mac OS X
				Begin BuildProjectStep Build
				End
				Begin CopyFilesBuildStep CopyFiles1
					AppliesTo = 0
					Architecture = 0
					Destination = 1
					Subdirectory = 
					FolderItem = Li4vUHJvZmlsZXMv
					FolderItem = Li4vR2VuZXRpYy5jb2Rlcw==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL1RyYW5zVGVybUhQL2V4cHRlcm0uZGF0
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL1RyYW5zVGVybUhQL3RyYW5zdGVybQ==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2JsYW5rLmh0bWw=
					FolderItem = Li4vZ2Vub21lU3RhdHMuSlNPTg==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL0htbWVyVXNlckd1aWRlLnBkZg==
					FolderItem = Li4vSGVscC8=
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL1JlZ3Vsb25EQi8=
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL01hYy9tYXN0
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL01hYy9tZW1l
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL01hYy90ZmFzdHg=
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL01hYy9hbGltYXNr
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL01hYy9obW1idWlsZA==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL01hYy9uaG1tZXI=
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL01hYy9tZW1lX3htbF90b19odG1s
					FolderItem = Li4vUHl0aG9uL2diazJ0YmwucHk=
					FolderItem = Li4vUHl0aG9uL2dlbmVwYXJzZS5weQ==
					FolderItem = Li4vUHl0aG9uL0htbUdlbi5weQ==
					FolderItem = Li4vUHl0aG9uL01hc3RHZW4ucHk=
					FolderItem = Li4vUHl0aG9uL09wZXJPbi5weQ==
					FolderItem = Li4vUHl0aG9uL3B0dF9jb252ZXJ0ZXIucHk=
					FolderItem = Li4vVEZfSE1Ncy8=
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL01hYy9jZC1oaXQtZXN0
					FolderItem = Li4vVEZfZmFtaWxpZXMv
					FolderItem = Li4vUHl0aG9uL0Jpb1B5dGhvblZlcnNpb24ucHk=
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL01hYy9obW1zZWFyY2g=
					FolderItem = Li4vUHl0aG9uL1JlcGVhdEdlbi5weQ==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL01hYy9tZXNoY2x1c3Q=
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2NvbGxlY3RmX2V4cG9ydC50c3Y=
					FolderItem = Li4vUHl0aG9uL1Byb3RGYW1pbFkucHk=
					FolderItem = Li4vUHl0aG9uL2dldHByb3QucHk=
					FolderItem = Li4vLi4vQ2FsaWJyYXRlZFByb2ZpbGVzLw==
					FolderItem = Li4vUHl0aG9uL3VuaXByb3QyZ2VucGVwdC5weQ==
					FolderItem = Li4vLi4vQ1J0YWdCYXNlLw==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL01hYy90ZmFzdHg=
					FolderItem = Li4vUmVnUHJlY2lzZURhdGEv
					FolderItem = Li4vUHl0aG9uL0V4dHJhY3RGcmFnbWVudC5weQ==
					FolderItem = Li4vUHl0aG9uL1Rlcm1HZW4ucHk=
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2htbWxpYi5obW0=
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2htbWxpYi5obW0uaDNm
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2htbWxpYi5obW0uaDNp
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2htbWxpYi5obW0uaDNt
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2htbWxpYi5obW0uaDNw
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL0NvcnluZVJlZ05ldC8=
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2htbWxpYkwuaG1t
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2htbWxpYkwuaG1tLmgzZg==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2htbWxpYkwuaG1tLmgzaQ==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2htbWxpYkwuaG1tLmgzbQ==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2htbWxpYkwuaG1tLmgzcA==
					FolderItem = Li4vUHl0aG9uL21hdGNoZXNfc2NvcmVfYW5hbHlzaXMucHk=
					FolderItem = Li4vUHl0aG9uL2NvbGxlY3Rfc3RhdHMucHk=
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2htbWxpYkwuaG1t
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2htbWxpYkwuaG1tLmgzZg==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2htbWxpYkwuaG1tLmgzaQ==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2htbWxpYkwuaG1tLmgzbQ==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2htbWxpYkwuaG1tLmgzcA==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL25obW1lcl9saWIuaG1t
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL25obW1lcl9saWIuaG1tLmgzZg==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL25obW1lcl9saWIuaG1tLmgzaQ==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL25obW1lcl9saWIuaG1tLmgzbQ==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL25obW1lcl9saWIuaG1tLmgzcA==
					FolderItem = Li4vUHl0aG9uL2FkZF90ZmJzX3RvX2diay5weQ==
					FolderItem = Li4vUHl0aG9uL3RmX2NsYXNzaWZpZXIucHk=
				End
			End
			Begin BuildStepList Windows
				Begin BuildProjectStep Build
				End
				Begin CopyFilesBuildStep CopyFiles3
					AppliesTo = 0
					Architecture = 0
					Destination = 1
					Subdirectory = 
					FolderItem = Li4vUHJvZmlsZXMv
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL1RyYW5zVGVybUhQL2V4cHRlcm0uZGF0
					FolderItem = Li4vR2VuZXRpYy5jb2Rlcw==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL1dpbjMyL3RyYW5zdGVybS5leGU=
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL1dpbjMyL2FsaW1hc2suZXhl
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL1dpbjMyL2N5Z2djY19zLTEuZGxs
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL1dpbjMyL2N5Z3dpbjEuZGxs
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL1dpbjMyL2htbWJ1aWxkLmV4ZQ==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL1dpbjMyL25obW1lci5leGU=
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2JsYW5rLmh0bWw=
					FolderItem = Li4vZ2Vub21lU3RhdHMuSlNPTg==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL0htbWVyVXNlckd1aWRlLnBkZg==
					FolderItem = Li4vSGVscC8=
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL1dpbjMyL21hc3QuZXhl
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL1dpbjMyL21lbWUuZXhl
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL1dpbjMyL2xpYmdjY19zX2R3Mi0xLmRsbA==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL1dpbjMyL2xpYnN0ZGMlMkIlMkItNi5kbGw=
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL1dpbjMyL2xpYndpbnB0aHJlYWQtMS5kbGw=
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL1JlZ3Vsb25EQi8=
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL1dpbjMyL3RmYXN0eC5leGU=
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL01hYy9tZW1lX3htbF90b19odG1s
					FolderItem = Li4vUHl0aG9uL2diazJ0YmwucHk=
					FolderItem = Li4vUHl0aG9uL2dlbmVwYXJzZS5weQ==
					FolderItem = Li4vUHl0aG9uL0htbUdlbi5weQ==
					FolderItem = Li4vUHl0aG9uL01hc3RHZW4ucHk=
					FolderItem = Li4vUHl0aG9uL09wZXJPbi5weQ==
					FolderItem = Li4vUHl0aG9uL3B0dF9jb252ZXJ0ZXIucHk=
					FolderItem = Li4vVEZfSE1Ncy8=
					FolderItem = Li4vVEZfZmFtaWxpZXMv
					FolderItem = Li4vUHl0aG9uL0Jpb1B5dGhvblZlcnNpb24ucHk=
					FolderItem = Li4vUHl0aG9uL1JlcGVhdEdlbi5weQ==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2NvbGxlY3RmX2V4cG9ydC50c3Y=
					FolderItem = Li4vUHl0aG9uL1Byb3RGYW1pbFkucHk=
					FolderItem = Li4vLi4vQ1J0YWdCYXNlLw==
					FolderItem = Li4vLi4vQ2FsaWJyYXRlZFByb2ZpbGVzLw==
					FolderItem = Li4vUmVnUHJlY2lzZURhdGEv
					FolderItem = Li4vUHl0aG9uL0V4dHJhY3RGcmFnbWVudC5weQ==
					FolderItem = Li4vUHl0aG9uL1Rlcm1HZW4ucHk=
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2htbWxpYi5obW0=
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2htbWxpYi5obW0uaDNm
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2htbWxpYi5obW0uaDNp
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2htbWxpYi5obW0uaDNt
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2htbWxpYi5obW0uaDNw
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL0NvcnluZVJlZ05ldC8=
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2htbWxpYkwuaG1t
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2htbWxpYkwuaG1tLmgzZg==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2htbWxpYkwuaG1tLmgzaQ==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2htbWxpYkwuaG1tLmgzbQ==
					FolderItem = Li4vQnVpbGRfcmVzb3VyY2VzL2htbWxpYkwuaG1tLmgzcA==
					FolderItem = Li4vUHl0aG9uL21hdGNoZXNfc2NvcmVfYW5hbHlzaXMucHk=
					FolderItem = Li4vUHl0aG9uL2NvbGxlY3Rfc3RhdHMucHk=
				End
			End
#tag EndBuildAutomation
